def errors(err_code):
    err_dict = {0:('OP_ERR_NONE', '정상처리'),
                -10 :('OP_ERR_FAIL', '실패'),
                -100:('OP_ERR_LOGIN', '사용자정보교환실패'),
                -101:('OP_ERR_CONNECT', '서버접속실패'),
                -102:('OP_ERR_VERSION', '버전처리실패'),
                -103:('OP_ERR_FIREWALL', '개인방화벽실패'),
                -104:('OP_ERR_MEMORY', '메모리보호실패'),
                -105:('OP_ERR_INPUT', '함수입력값실패'),
                -106:('OP_ERR_SOCKET_CLOSED', '통신연결종료'),
                -200:('OP_ERR_PRICE_SEARCH_OVERFLOW', '시세조회과부하'),
                -201:('OP_ERR_RQ_STRUCT_FAIL', '전문작성초기화실패'),
                -202:('OP_ERR_RQ_STRING_FAIL', '전문작성입력값오류'),
                -203:('OP_ERR_NO_DATA', '데이터없음'),
                -204:('OP_ERR_OVER_MAX_DATA_QTY', '데이터조회가능한종목수초과'),
                -205:('OP_ERR_DATA_RCV_FAIL', '데이터수신실패'),
                -206:('OP_ERR_OVER_MAX_FID_QTY', '조회가능한FID수초과'),
                -207:('OP_ERR_REAL_CANCEL', '실시간해제오류'),
                -300:('OP_ERR_ORD_WRONG_INPUT', '입력값오류'),
                -301:('OP_ERR_ORD_WRONG_ACCT_PW', '계좌비밀번호틀림'),
                -302:('OP_ERR_OHTER_ACCT_USE', '타인계좌사용오류'),
                -303:('OP_ERR_ORD_2BILL_EXCESS', '주문가격20억원한도초과'),
                -304:('OP_ERR_ORD_5BILL_EXCESS', '주문가격50억원한도초과'),
                -305:('OP_ERR_ORD_1PER_EXCESS', '주문수량이 총 발행주식수의 1% 초과오류'),
                -306:('OP_ERR_ORD_3PER_EXCESS', '주문수량이 총 발행주식수의 3% 초과오류'),
                -307:('OP_ERR_ORD_SEND_FAIL', '주문실패'),
                -308:('OP_ERR_ORD_OVERFLOW', '주문전송과부하'),
                -309:('OP_ERR_ORD_300CONTRACT_EXCESS', '주문수량300개 초과'),
                -310:('OP_ERR_ORD_500CONTRACT_EXCESS', '주문수량500개 초과'),
                -340:('OP_ERR_ACCT_INFO_NOT_EXIST', '계좌정보없음'),
                -500:('OP_ERR_COMPANY_CODE_NOT_EXIST', '종목코드없음'),}
    
    result = err_dict[err_code]
    
    return result